### ISSUE TITLE
NBA gamelog functions not pulling in regular season data

### ISSUE THREAD

**Issue by gabeneslin** [sportsdataverse/hoopR#104]
The when trying to load in regular season data the NBA_leageugamelog function will return an error. For example, calling both
 nba_leaguegamelog(season = '2021-22', 
                  player_or_team = "T")

or 
nba_leaguegamelog(season = '2021-22', 
                  player_or_team = "T",
                  season_type = "Regular Season"
                  )

return the following error messages: "Request failed [400]. Retrying in 1.4 seconds...
Request failed [400]. Retrying in 2.9 seconds...
2023-01-10 14:44:55: Invalid arguments or no league game log data for 2021-22 available!
Error in nba_leaguegamelog(season = "2021-22", player_or_team = "T", ) : 
  object 'df_list' not found"

This error does not occur when using the same function to pull in playoff data, as the following runs just fine:

nba_leaguegamelog(season = '2021-22', 
                  player_or_team = "T",
                  season_type = "Playoffs"
)

This error with getting regular season data seems to also exist for other NBA log functions such as nba_playergamelog which also returns an error for regular season data but works for playoff data.

Thanks

**Comment by TommasoDelPrete** [comment]
I have the same issue

This is the error:

nba_leaguegamelog(season = '2021-22',
+                   player_or_team = "T",
+                   season_type = "Regular Season"
+ )
Request failed [500]. Retrying in 1 seconds...
Request failed [500]. Retrying in 1 seconds...
2023-03-07 19:07:42: Invalid arguments or no league game log data for 2021-22 available!
Error in nba_leaguegamelog(season = "2021-22", player_or_team = "T", season_type = "Regular Season") : 
  object 'df_list' not found

**Comment by rossdrucker** [comment]
What version of the package do you have installed? I believe he GitHub version of the package (see the README for install directions) has resolved this... think it was due to the API endpoints changing around a bit but was addressed in #102

**Comment by gabeneslin** [comment]
Thanks, installing the GitHub version instead of the version on CRAN appears to have fixed this issue for me.

**Comment by TommasoDelPrete** [comment]
Thank you, by installing the library from GitHub problem is fixed

________________________________
Da: Ross Drucker ***@***.***>
Inviato: martedì 7 marzo 2023 18:54
A: sportsdataverse/hoopR ***@***.***>
Cc: Tommaso Del Prete - ***@***.*** ***@***.***>; Comment ***@***.***>
Oggetto: Re: [sportsdataverse/hoopR] NBA gamelog functions not pulling in regular season data (Issue #104)


What version of the package do you have installed? I believe he GitHub version of the package (see the README for install directions) has resolved this... think it was due to the API endpoints changing around a bit but was addressed in #102<https://github.com/sportsdataverse/hoopR/pull/102>
