### ISSUE TITLE
nba_leaguegamelog function 400 error when running on Mac

### ISSUE THREAD

**Issue by schmid07** [sportsdataverse/hoopR#86]
**Describe the bug**
When running the nba_leaguegamelog function on a Mac using version 1.7.0 of hoopR, I get an error when using "Regular Season" in the season_type argument.  

This function works when I run on Windows using both "Regular Season" or "Playoffs" in the sesaon_type argument. 

It also works on the Mac when I pass in "Playoffs" in the season_type argument (but doesn't work when using "Regular Season".)

I've tried running the function using chrome and then safari as default browser.  I've also tried clearing browser cache and cookies.  I'm running the script in RStudio.

This is the error shown when running the function on Mac:

Request failed [400]. Retrying in 1.9 seconds...
Request failed [400]. Retrying in 2.1 seconds...
2022-07-30 14:11:14: Invalid arguments or no league game log data for 2021 available!
Error in nba_leaguegamelog(season = 2021, season_type = "Regular Season",  : 
  object 'df_list' not found

**To Reproduce**

```
library(hoopR)

test <- nba_leaguegamelog(season = 2021, season_type = "Regular Season", 
                          player_or_team = "T") 
```

Thanks,

Bill

**Comment by schmid07** [comment]
It looks like when I ran on Windows (where it was working), I was using version 1.5.0 of hoopR.  When I switched to 1.8.0, I got the same error message as when running on Mac.  And when I switched back to 1.5.0 on the Mac, the function worked. So it seems like the function works in v. 1.5.0, but was having some issues with 1.7.0 and then also when I updated to 1.8.0.  

Thanks.

**Comment by murrayjw** [comment]
I was having the same problem and had a quick look at the code. Looks like the problem is coming from a new default argument (`params = list()`) that was added to the `.nba_headers()` function.  That function  uses `httr::GET` to request the data from the API. The `params` argument is passed to httr::GET in the `query` argument but it is empty for the `nba_leaguegamelog` function. If you remove the `query` argument the data is returned as it was before. 

So if this:

```
res <- httr::RETRY("GET", url, query = params, httr::add_headers(.headers = headers))

```
is changed to this:
```
if(length(params) == 0) {
   res <- httr::RETRY("GET", url, httr::add_headers(.headers = headers))
} else {
    res <- httr::RETRY("GET", url, query = params, httr::add_headers(.headers = headers))
}

```

in the `.nba_headers()` function, everything works. The `params` argument gets used elsewhere (e.g. `hoopR::nba_scoreboard`. so you need some logic to deal with the case where params are empty

**Comment by saiemgilani** [comment]
You're a lifesaver, thanks

**Comment by murrayjw** [comment]
No problem! Anytime
